AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SubnetID:
    Type: "AWS::EC2::Subnet::Id"
  VPCID:
    Type: "AWS::EC2::VPC::Id"
  DataHubBaseUrl:
    Type: "String"
    Default: "https://staging.acryl.io/gms"
  DataHubAccessToken:
    Type: "String"
    NoEcho: Yes
  AwsAccessKeyId:
    Type: "String"
    NoEcho: Yes
  AwsSecretAccessKey:
    Type: "String"
    NoEcho: Yes
  AwsRegion:
    Type: "String"
  AwsCommandQueueUrl:
    Type: "String"
    Default: "https://sqs.us-west-2.amazonaws.com/795586375822/datahub-executor-command-test"
  AwsCommandQueueArn:
    Type: "String"
    Default: "arn:aws:sqs:us-west-2:795586375822:datahub-executor-command-test"
  TaskCpu:
    Type: "String"
    Default: "1024"
    Description: "The ECS Task CPU value, check https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html"
    AllowedValues:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
  TaskMemory:
    Type: "String"
    Default: "2048"
    Description: "The ECS Task Memory value (MiB), check https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html"
    AllowedValues:
      - 512
      - 1024
      - 2048
      - 4096
      - 5120
      - 6144
      - 7168
      - 8192
      - 9216
      - 10240
      - 11264
      - 12288
      - 13312
      - 14336
      - 15360
      - 16384
      - 17408
      - 18432
      - 19456
      - 20480
      - 21504
      - 22528
      - 23552
      - 24576
      - 25600
      - 26624
      - 27648
      - 28672
      - 29696
      - 30720

### ECS Cluster ###
Resources:
  DataHubAccessTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "/${AWS::StackName}/DataHubAccessToken"
      Description: !Sub "${AWS::StackName}: Secrets for DataHubAccessToken"
      SecretString: !Ref DataHubAccessToken
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${AWS::StackName}"
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${AWS::StackName}-log-group"
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-task-role"
      #RoleName: !Sub "datahub-ingestion-task-role"
      Policies:
        - PolicyName: ssmmessages-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Action: 
                - ssmmessages:CreateControlChannel
                - ssmmessages:CreateDataChannel
                - ssmmessages:OpenControlChannel
                - ssmmessages:OpenDataChannel
              Effect: Allow
              Resource: "*"
        - PolicyName: logs-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Action: 
                - logs:DescribeLogGroups
              Effect: Allow
              Resource: "*"
        - PolicyName: logs-streams-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Action:
                - logs:CreateLogStream
                - logs:DescribeLogStreams
                - logs:PutLogEvents
              Effect: Allow
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ecs/${AWS::StackName}-log-group:*"
        - PolicyName: sqs-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Action:
                - sqs:ChangeMessageVisibility
                - sqs:DeleteMessage
                - sqs:ReceiveMessage
                - sqs:GetQueueUrl
              Effect: Allow
              Resource: !Ref AwsCommandQueueArn
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-execution-role"
      #RoleName: !Sub "datahub-ingestion-execution-role"
      Policies:
        - PolicyName: logs-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Action:
                - logs:DescribeLogGroups
              Resource: "*"
              Effect: Allow
        - PolicyName: logs-streams-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Action:
                - logs:CreateLogStream
                - logs:DescribeLogStreams
                - logs:PutLogEvents
              Effect: Allow
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ecs/${AWS::StackName}-log-group:*"
        - PolicyName: secretsmanager-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Action:
                - secretsmanager:GetSecretValue
                #- ssm:GetParameters
                #- kms:Decrypt
              Effect: Allow
              Resource: !Sub "${DataHubAccessTokenSecret}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ContainerSecurityGroup
      GroupDescription: Security group for container
      VpcId: !Ref VPCID
      #SecurityGroupIngress:
      #  - IpProtocol: tcp
      #    FromPort: 80
      #    ToPort: 80
      #    CidrIp: 0.0.0.0/0

### Task Definition and ECS Service ###
  TaskDefinition:
    DependsOn: DataHubAccessTokenSecret
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${AWS::StackName}-task"
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      TaskRoleArn: !Ref TaskRole
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: !Sub "${AWS::StackName}-container"
          Image: 795586375822.dkr.ecr.us-west-2.amazonaws.com/acryl-sqs-remote-executor
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
          Secrets:
            - Name: DATAHUB_ACCESS_TOKEN
              ValueFrom: !Sub "${DataHubAccessTokenSecret}"
          Environment: 
            - Name: DATAHUB_BASE_URL
              Value: !Ref DataHubBaseUrl
            - Name: AWS_ACCESS_KEY_ID
              Value: !Ref AwsAccessKeyId
            - Name: AWS_SECRET_ACCESS_KEY
              Value: !Ref AwsSecretAccessKey
            - Name: AWS_SESSION_TOKEN
              Value: ""
            - Name: AWS_REGION 
              Value: !Ref AwsRegion
            - Name: AWS_COMMAND_QUEUE_URL
              Value: !Ref AwsCommandQueueUrl
      RequiresCompatibilities:
        - EC2
        - FARGATE
  ECSService:
    DependsOn: Cluster
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub "${AWS::StackName}-service"
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      EnableExecuteCommand: true
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetID
          SecurityGroups:
            - !GetAtt ContainerSecurityGroup.GroupId
